// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.cmucdu.ecommerce.domain.product;

import edu.cmucdu.ecommerce.dao.product.ProductPicDao;
import edu.cmucdu.ecommerce.domain.product.ProductPicDataOnDemand;
import edu.cmucdu.ecommerce.domain.product.ProductPicIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductPicIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductPicIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductPicIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductPicIntegrationTest: @Transactional;
    
    @Autowired
    private ProductPicDataOnDemand ProductPicIntegrationTest.dod;
    
    @Autowired
    ProductPicDao ProductPicIntegrationTest.productPicDao;
    
    @Test
    public void ProductPicIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to initialize correctly", dod.getRandomProductPic());
        long count = productPicDao.count();
        Assert.assertTrue("Counter for 'ProductPic' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductPicIntegrationTest.testFind() {
        ProductPic obj = dod.getRandomProductPic();
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to provide an identifier", id);
        obj = productPicDao.findOne(id);
        Assert.assertNotNull("Find method for 'ProductPic' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductPic' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductPicIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to initialize correctly", dod.getRandomProductPic());
        long count = productPicDao.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductPic', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductPic> result = productPicDao.findAll();
        Assert.assertNotNull("Find all method for 'ProductPic' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductPic' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductPicIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to initialize correctly", dod.getRandomProductPic());
        long count = productPicDao.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductPic> result = productPicDao.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ProductPic' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductPic' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductPicIntegrationTest.testFlush() {
        ProductPic obj = dod.getRandomProductPic();
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to provide an identifier", id);
        obj = productPicDao.findOne(id);
        Assert.assertNotNull("Find method for 'ProductPic' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductPic(obj);
        Integer currentVersion = obj.getVersion();
        productPicDao.flush();
        Assert.assertTrue("Version for 'ProductPic' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductPicIntegrationTest.testSaveUpdate() {
        ProductPic obj = dod.getRandomProductPic();
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to provide an identifier", id);
        obj = productPicDao.findOne(id);
        boolean modified =  dod.modifyProductPic(obj);
        Integer currentVersion = obj.getVersion();
        ProductPic merged = productPicDao.save(obj);
        productPicDao.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductPic' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductPicIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to initialize correctly", dod.getRandomProductPic());
        ProductPic obj = dod.getNewTransientProductPic(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductPic' identifier to be null", obj.getId());
        productPicDao.save(obj);
        productPicDao.flush();
        Assert.assertNotNull("Expected 'ProductPic' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductPicIntegrationTest.testDelete() {
        ProductPic obj = dod.getRandomProductPic();
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductPic' failed to provide an identifier", id);
        obj = productPicDao.findOne(id);
        productPicDao.delete(obj);
        productPicDao.flush();
        Assert.assertNull("Failed to remove 'ProductPic' with identifier '" + id + "'", productPicDao.findOne(id));
    }
    
}
