// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.cmucdu.ecommerce.domain.product;

import edu.cmucdu.ecommerce.domain.product.ProductPicIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProductPicIntegrationTest_Roo_Configurable {
    
    declare @type: ProductPicIntegrationTest: @Configurable;
    
}
