// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.cmucdu.ecommerce.user;

import edu.cmucdu.ecommerce.user.BuyerDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BuyerDataOnDemand_Roo_Configurable {
    
    declare @type: BuyerDataOnDemand: @Configurable;
    
}
