// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.cmucdu.ecommerce.user;

import edu.cmucdu.ecommerce.user.Seller;
import javax.persistence.Entity;

privileged aspect Seller_Roo_Jpa_Entity {
    
    declare @type: Seller: @Entity;
    
}
