// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.cmucdu.ecommerce.domain.user.security;

import edu.cmucdu.ecommerce.domain.user.security.Principal;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Principal_Roo_Configurable {
    
    declare @type: Principal: @Configurable;
    
}
